# -*- coding: utf-8 -*-
"""Yoruba_TTS_App_DG-AOG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14O9Npb7Yd3xDB_GIM6dLMX06ibcMTu47
"""

pip install gradio

import gradio as gr
import requests

# Yoruba text auto-formatting dictionary
yoruba_map = {
    "nife": "nífẹ̀ẹ́",
    "mo": "Mo",
    "re": "rẹ",
    "e": "ẹ",
    "je": "jẹ",
    "gba": "gbọ́",
    "o": "Ọ",
    "odun": "Ọdún",
    "dara": "dára",
    "pupo": "púpọ̀",
    "se": "ṣé",
    "bawo": "Báwo",
    "ni": "ní",
    "ile": "ilé",
    "ise": "ìṣẹ́",
    "owo": "òwò",
    "orin": "ọ̀rìn",
    "oko": "ọkọ",
    "iya": "ìyá",
    "baba": "bàbá",
    "omo": "ọmọ",
    "ile-iwe": "ilé-ìwé",
    "owo": "ọ̀wọ̀",
    "alafia": "àlàáfíà",
    "aiku": "àìkú",
    "aabo": "ààbò",
    "aare": "ààrẹ́",
    "ojo": "ọjọ́",
    "ayika": "àyíká",
    "idunnu": "ìdùnnú",
    "ifokanbale": "ìfẹ́kànbalẹ̀",
    "ayemi": "àyé mi",
    "ire": "ìrẹ̀",
    "igba": "ìgbà",
    "ibanuje": "ìbànújẹ́",
    "ayewo": "àyẹ̀wò",
    "arin": "àárín",
    "alubarika": "àlubaríkà",
    "agun": "àgùntàn",
    "asiko": "àsìkò",
    "aago": "ààgò",
    "ofe": "òfé",
    "aaye": "àyé",
}

# Formatter function
def format_yoruba_text(text):
    words = text.lower().split()
    formatted = []
    for word in words:
        if word in yoruba_map:
            formatted.append(yoruba_map[word])
        else:
            formatted.append(word)
    return " ".join(formatted).capitalize()

# TTS function
def text_to_speech(text, voice_id, api_key):
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}"
    headers = {
        "xi-api-key": api_key,
        "Content-Type": "application/json"
    }
    payload = {
        "text": text,
        "voice_settings": {
            "stability": 0.5,
            "similarity_boost": 0.75
        }
    }

    response = requests.post(url, headers=headers, json=payload)

    if response.status_code == 200:
        audio_path = "yoruba_output.mp3"
        with open(audio_path, "wb") as f:
            f.write(response.content)
        return audio_path, audio_path
    else:
        return None, f"❌ Error: {response.status_code} - {response.text}"

# Gradio app logic
def app_interface(yoruba_text, voice_id, api_key):
    formatted_text = format_yoruba_text(yoruba_text)
    audio, error = text_to_speech(formatted_text, voice_id, api_key)
    if audio:
        return audio, audio
    else:
        return None, error

# Gradio UI setup
demo = gr.Interface(
    fn=app_interface,
    inputs=[
        gr.Textbox(label="💬 Enter Yoruba Text"),
        gr.Textbox(label="🗣️ Voice ID"),
        gr.Textbox(label="🔐 API Key", type="password")
    ],
    outputs=[
        gr.Audio(label="🔊 Play Yoruba Speech"),
        gr.File(label="⬇️ Download Audio File")
    ],
    title="DG-AOG Yoruba TTS App",
    description="Type Yoruba text with tones, choose a voice ID, and enter your ElevenLabs API key. The system formats your text and speaks it aloud. Kí Ọlọ́run bù kún ẹ"
)

demo.launch(share=True)

